spring:
  profiles:
    active: dev

server:
  port: 8082

headers:
  contentSecurityPolicy: "script-src 'self'"

userIPHeaderName: x-forwarded-for
#append a whitespace character at the end of prefix (before newline) if you want it to be separate from main message body
userIPLoggingPrefix: from IP
userIPLoggingMDCkey: userIP

h2:
  console:
    enabled: true

sqlms:
  saved-queries-dir: "./templates/"
  datasources:
    - name: production
      jdbcUrl: ${JDBC_URL}
      username: user
      password: pass
      driverClassName: org.postgresql.Driver
logging:
  level:
    root: info
